site_name: MkDocs Plugins
site_author: Roberto Prevato
site_description: The documentation of Neoteroi MkDocs Plugins.
site_url: https://www.neoteroi.dev/mkdocs-plugins/
repo_name: Neoteroi/mkdocs-plugins
repo_url: https://github.com/Neoteroi/mkdocs-plugins
edit_uri: ""

nav:
  - Overview: index.md
  - Introduction: intro.md
  - Plugins:
      - Cards: cards.md
      - Timeline: timeline.md
      - Gantt: gantt.md
      - OpenAPI Docs: ./web/oad.md
      - Spantable: spantable.md
  - Info:
      - Credits: credits.md
      - About: about.md

theme:
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  name: "material"
  custom_dir: overrides/
  highlightjs: true
  favicon: img/neoteroi.ico
  logo: img/neoteroi-w.svg
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra_css:
  - css/extra.css
  - css/neoteroi.css

markdown_extensions:
  - admonition
  - neoteroi.spantable
  - neoteroi.timeline
  - neoteroi.cards
  - neoteroi.projects
  - markdown.extensions.codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
